2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.address`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.address` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.automotive`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.automotive` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.bank`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Specified locale `en_US` is not available for provider `faker.providers.bank`. Locale reset to `en_GB` for this provider. (factory.py:88)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.barcode`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.barcode` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.color`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.color` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.company`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.company` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.credit_card`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.credit_card` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.currency`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.currency` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.date_time`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.date_time` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.emoji` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:108)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.file` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:108)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.geo`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.geo` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.internet`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.internet` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.isbn`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.isbn` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.job`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.job` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.lorem`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.lorem` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.misc`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.misc` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.passport`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.passport` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.person`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.person` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.phone_number`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.phone_number` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.profile` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:108)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.python` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:108)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.sbn` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:108)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Looking for locale `en_US` in provider `faker.providers.ssn`. (factory.py:78)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.ssn` has been localized to `en_US`. (factory.py:97)
2024-Sun-08 20:29:38 [   DEBUG] [faker.factory] Provider `faker.providers.user_agent` does not feature localization. Specified locale `en_US` is not utilized for this provider. (factory.py:108)
2024-Sun-08 20:29:38 [   DEBUG] [urllib3.connectionpool] Starting new HTTPS connection (1): simple-books-api.glitch.me:443 (connectionpool.py:1053)
2024-Sun-08 20:29:40 [   DEBUG] [urllib3.connectionpool] https://simple-books-api.glitch.me:443 "GET /books?type=fiction&limit=100 HTTP/1.1" 400 81 (connectionpool.py:547)
2024-Sun-08 20:29:40 [    INFO] [testsimpleBookApi.test01_getbooks] api book validation type fiction beyond limit (test01_getbooks.py:65)
